name: Test
on: 
  pull_request:
    paths: ['go/**/*.go']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v4
      - use: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test go/excellent/*.go